version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
    reviewers:
      - "quortex/devops"
    rebase-strategy: "disabled"

  # Maintain dependencies for go modules
  - package-ecosystem: "gomod"
    schedule:
      interval: "weekly"
    reviewers:
      - "quortex/devops"
    rebase-strategy: "disabled"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    schedule:
      interval: "weekly"
    reviewers:
      - "quortex/devops"
    rebase-strategy: "disabled"
