apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  template:
    spec:
      containers:
        - name: aws-ec2-adapter
          image: quortexio/aws-ec2-adapter:1.0.0
          args:
            - -addr
            - ":8008"
          ports:
            - containerPort: 8008
          env:
            - name: QX_CONFIGURATION_PATH
              value: /config/config.yaml
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: awsKeyId
                  name: aws-ec2-plugin
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: awsSecretKey
                  name: aws-ec2-plugin
          volumeMounts:
            - mountPath: /config/config.yaml
              name: config
              subPath: config.yaml
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      volumes:
        - configMap:
            defaultMode: 420
            name: aws-ec2-plugin
          name: config
