manager:
  logs:
    verbosity: 4
  image:
    tag: latest
  resources:
    limits:
      cpu: 100m
      memory: 30Mi
    requests:
      cpu: 100m
      memory: 20Mi

awsEC2Plugin:
  enabled: true
  image:
    tag: latest
  resources:
    limits:
      cpu: 100m
      memory: 30Mi
    requests:
      cpu: 100m
      memory: 20Mi
  secret: aws-ec2-plugin
  region: eu-west-1
  tags:
    quortex.io/owner/environment: development
    quortex.io/owner/service: kubestitute
    quortex.io/owner/identifier: kindcluster

kubeRBACProxy:
  enabled: false

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: metrics
