# Default values for kubestitute.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

manager:
  clusterAutoscaler:
    namespace: kube-system
    name: cluster-autoscaler-status
  logs:
    # Logs verbosity:
    #  0 => panic
    #  1 => error
    #  2 => warning
    #  3 => info
    #  4 => debug
    verbosity: 3
    enableDevLogs: false

  image:
    repository: quortexio/kubestitute
    tag: latest
    pullPolicy: IfNotPresent
  resources: {}

kubeRBACProxy:
  enabled: true
  image:
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    tag: v0.5.0
    pullPolicy: IfNotPresent
  resources: {}

awsEC2Plugin:
  enabled: true
  image:
    repository: quortexio/aws-ec2-adapter
    tag: develop
    pullPolicy: IfNotPresent
  resources: {}
  secret: aws-ec2-plugin
  region: ""
  tags: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

## Annotations to be added to pods
##
podAnnotations: {}

## Annotations to be added to deployment
##
deploymentAnnotations: {}


# How long to wait for pods to stop gracefully
terminationGracePeriod: 30

nodeSelector: {}

tolerations: []

affinity: {}
