# Default values for kubestitute.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

aws:
  # -- The region in which the cluster resides.
  region: ""
  # -- The access key id of a user with necessary permissions.
  accessKeyID: ""
  # -- The secret access key of a user with necessary permissions.
  secretAccessKey: ""

manager:
  clusterAutoscaler:
    # -- The Cluster Autoscaler namespace.
    namespace: kube-system
    # -- The Cluster Autoscaler status configmap name.
    name: cluster-autoscaler-status
    # -- Whether to parse the Cluster Autoscaler status configmap in legacy format, used by cluster-autoscaler up to version 1.29.
    legacyFormat: false

  priorityExpander:
    enabled: false
    # -- All the following values should not be modified.
    # -- Name of the Priority Expander object.
    name: priority-expander-default
    # -- Namespace of the Priority Expander object.
    namespace: kubestitute-system
    # -- This name should not be changed. This is the exact name cluster autoscaler is looking for.
    clusterAutoscalerConfigMap: cluster-autoscaler-priority-expander
    # -- Default template, no priorities.
    template: |-
      5:
       - .*

  logs:
    # -- Logs verbosity:
    #
    #  0 => panic
    #  1 => error
    #  2 => warning
    #  3 => info
    #  4 => debug
    verbosity: 3
    enableDevLogs: false

  # -- AutoScaling Groups polling interval (used to generate custom metrics about ASGs).
  asgPollInterval: 30

  # -- The timeout in seconds for pods eviction on Instance deletion.
  evictionTimeout: 300

  # -- The maximum number of concurrent Reconciles which can be run for Instances.
  instancesMaxConcurrentReconciles: 10

  image:
    # -- Kubestitute manager image repository.
    repository: quortexio/kubestitute
    # -- Kubestitute manager image tag.
    tag: ""
    # -- Kubestitute manager image pull policy.
    pullPolicy: IfNotPresent

  livenessProbe:
    httpGet:
      # -- Path of the manager liveness probe.
      path: /healthz
      # -- Name or number of the manager liveness probe port.
      port: 8081
    # -- Number of seconds before the manager liveness probe is initiated.
    initialDelaySeconds: 15
    # -- How often (in seconds) to perform the manager liveness probe.
    periodSeconds: 20

  readinessProbe:
    httpGet:
      # -- Path of the manager readiness probe.
      path: /readyz
      # -- Name or number of the manager readiness probe port.
      port: 8081
    # -- Number of seconds before the manager readiness probe is initiated.
    initialDelaySeconds: 5
    # -- How often (in seconds) to perform the manager readiness probe.
    periodSeconds: 10

  # -- Kubestitute manager container required resources.
  resources: {}

kubeRBACProxy:
  enabled: true
  image:
    # -- kube-rbac-proxy image repository.
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    # -- kube-rbac-proxy image tag.
    tag: v0.8.0
    # -- kube-rbac-proxy image pull policy.
    pullPolicy: IfNotPresent
  # --  kube-rbac-proxy container required resources.
  resources: {}

# -- Number of desired pods.
replicaCount: 1

# -- Security contexts to set for all containers of the pod.
securityContext:
  {}
  # runAsNonRoot: true

# --  A list of secrets used to pull containers images.
imagePullSecrets: []

# --  Helm's name computing override.
nameOverride: ""

# --  Helm's fullname computing override.
fullnameOverride: ""

# --  Annotations to be added to pods.
podAnnotations: {}

# -- serviceAccount setup
serviceAccount:
  annotations: {}

# --  Annotations to be added to deployment.
deploymentAnnotations: {}

# --  How long to wait for pods to stop gracefully.
terminationGracePeriod: 30

# --  Node labels for Kubestitute pod assignment.
nodeSelector: {}

# --  Node tolerations for Kubestitute scheduling to nodes with taints.
tolerations: []

# --  Affinity for Kubestitute pod assignment.
affinity: {}

serviceMonitor:
  # -- Create a prometheus operator ServiceMonitor.
  enabled: false
  # -- Labels added to the ServiceMonitor.
  additionalLabels: {}
  # -- Annotations added to the ServiceMonitor.
  annotations: {}
  # -- Override prometheus operator scrapping interval.
  interval: ""
  # -- Override prometheus operator scrapping timeout.
  scrapeTimeout: ""
  # -- Relabellings to apply to samples before scraping.
  relabelings: []

# -- Extra objects to deploy (value evaluated as a template).
extraObjects: []

# Network policy configuration.
networkPolicy:
  # -- Whether to enable kubestatic network policy.
  enabled: false
  # -- Ingress rules to add to the network policy
  extraIngress: []
#    - ports:
#        - protocol: TCP
#          port: 8443
#      from:
#        - namespaceSelector:
#            matchLabels:
#              kubernetes.io/metadata.name: monitoring
#          podSelector:
#            matchLabels:
#              app.kubernetes.io/name: prometheus
#              operator.prometheus.io/name: prometheus-kube-prometheus-prometheus
# -- Egress rules to add to the network policy
extraEgress: []
