// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Address address
//
// swagger:model Address
type Address struct {

	// AllocationId is the ID representing the allocation of the address for use with EC2-VPC.
	AllocationID string `json:"allocation_id,omitempty"`

	// AssociationId is the ID representing the association of the address with an instance in a VPC.
	AssociationID string `json:"association_id,omitempty"`

	// InstanceId is the ID of the instance that the address is associated with (if any).
	InstanceID string `json:"instance_id,omitempty"`

	// NetworkInterfaceId is the ID of the network interface.
	NetworkInterfaceID string `json:"network_interface_id,omitempty"`

	// PublicIp is the Elastic IP address.
	PublicIP string `json:"public_ip,omitempty"`

	// Tags is any tags assigned to the Elastic IP address.
	Tags map[string]string `json:"tags,omitempty"`
}

// Validate validates this address
func (m *Address) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Address) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Address) UnmarshalBinary(b []byte) error {
	var res Address
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
