// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateSecurityGroupRequest create security group request
//
// swagger:model CreateSecurityGroupRequest
type CreateSecurityGroupRequest struct {

	// A description for the security group. This is informational only.
	Description string `json:"description,omitempty"`

	// The name of the security group.
	Name string `json:"name,omitempty"`

	// The ID of the VPC. Required for EC2-VPC.
	VpcID string `json:"vpc_id,omitempty"`
}

// Validate validates this create security group request
func (m *CreateSecurityGroupRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateSecurityGroupRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateSecurityGroupRequest) UnmarshalBinary(b []byte) error {
	var res CreateSecurityGroupRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
