// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DetachInstancesRequest detach instances request
//
// swagger:model DetachInstancesRequest
type DetachInstancesRequest struct {

	// The IDs of the instances. You can specify up to 20 instances.
	InstanceIds []string `json:"instance_ids"`

	// Indicates whether the Auto Scaling group decrements the desired capacity
	// value by the number of instances detached.
	ShouldDecrementDesiredCapacity bool `json:"should_decrement_desired_capacity,omitempty"`

	// Indicates whether the Instances should be terminated.
	ShouldTerminateInstances bool `json:"should_terminate_instances,omitempty"`
}

// Validate validates this detach instances request
func (m *DetachInstancesRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DetachInstancesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DetachInstancesRequest) UnmarshalBinary(b []byte) error {
	var res DetachInstancesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
