// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GroupIdentifier group identifier
//
// swagger:model GroupIdentifier
type GroupIdentifier struct {

	// The ID of the security group.
	GroupID string `json:"group_id,omitempty"`

	// The name of the security group.
	GroupName string `json:"group_name,omitempty"`
}

// Validate validates this group identifier
func (m *GroupIdentifier) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GroupIdentifier) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GroupIdentifier) UnmarshalBinary(b []byte) error {
	var res GroupIdentifier
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
