# permissions for end users to view priorityexpanders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: priorityexpander-viewer-role
rules:
- apiGroups:
  - core.kubestitute.quortex.io
  resources:
  - priorityexpanders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kubestitute.quortex.io
  resources:
  - priorityexpanders/status
  verbs:
  - get
