# permissions for end users to edit priorityexpanders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: priorityexpander-editor-role
rules:
- apiGroups:
  - core.kubestitute.quortex.io
  resources:
  - priorityexpanders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubestitute.quortex.io
  resources:
  - priorityexpanders/status
  verbs:
  - get
