apiVersion: core.kubestitute.quortex.io/v1alpha1
kind: Instance
metadata:
  name: instance-sample
spec:
  # The AutoScaling Group name in which to trigger a new instance.
  autoscalingGroup: my-fallback-asg

  # Indicates whether Amazon EC2 Auto Scaling waits for the cooldown period to
  # complete before initiating a scaling activity to set your Auto Scaling group
  # to its new capacity. By default, Amazon EC2 Auto Scaling does not honor the
  # cooldown period during manual scaling activities.
  honorCooldown: false
