apiVersion: core.kubestitute.quortex.io/v1alpha1
kind: Instance
metadata:
  name: instance-sample
spec:
  # Add fields here
  asg: kubestitute
---
apiVersion: core.kubestitute.quortex.io/v1alpha1
kind: Instance
metadata:
  name: instance-sample2
spec:
  # Add fields here
  asg: kubestitute
---
apiVersion: core.kubestitute.quortex.io/v1alpha1
kind: Instance
metadata:
  name: instance-sample3
spec:
  # Add fields here
  asg: kubestitute
---
apiVersion: core.kubestitute.quortex.io/v1alpha1
kind: Instance
metadata:
  name: instance-sample4
spec:
  # Add fields here
  asg: kubestitute
---
apiVersion: core.kubestitute.quortex.io/v1alpha1
kind: Instance
metadata:
  name: instance-sample5
spec:
  # Add fields here
  asg: kubestitute
---
apiVersion: core.kubestitute.quortex.io/v1alpha1
kind: Instance
metadata:
  name: instance-sample6
spec:
  # Add fields here
  asg: kubestitute
---
apiVersion: core.kubestitute.quortex.io/v1alpha1
kind: Instance
metadata:
  name: instance-sample7
spec:
  # Add fields here
  asg: kubestitute
---
apiVersion: core.kubestitute.quortex.io/v1alpha1
kind: Instance
metadata:
  name: instance-sample8
spec:
  # Add fields here
  asg: kubestitute
---
apiVersion: core.kubestitute.quortex.io/v1alpha1
kind: Instance
metadata:
  name: instance-sample9
spec:
  # Add fields here
  asg: kubestitute
---
apiVersion: core.kubestitute.quortex.io/v1alpha1
kind: Instance
metadata:
  name: instance-sample10
spec:
  # Add fields here
  asg: kubestitute
