{{- if .Values.awsEC2Plugin.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubestitute.fullname" . }}
  labels:
    {{- include "kubestitute.labels" . | nindent 4 }}
data:
{{- with .Values.awsEC2Plugin }}
  ec2Adapter.yaml: |
    region: {{ .region }}
    {{- if .tags }}
    tags:
      {{- toYaml .tags | nindent 6 }}
    {{- else }}
    unsafe: true
    {{- end }}
{{- end }}
{{- end }}
