{{- if (not (has "" (list .Values.aws.accessKeyID .Values.aws.secretAccessKey))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubestitute.fullname" . }}
data:
{{- with .Values.aws }}
  accessKeyId: "{{ .accessKeyID | b64enc }}"
  secretAccessKey: "{{ .secretAccessKey | b64enc }}"
{{- end }}
{{- end }}
