// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAddSecurityGroupParams creates a new AddSecurityGroupParams object
// with the default values initialized.
func NewAddSecurityGroupParams() *AddSecurityGroupParams {
	var ()
	return &AddSecurityGroupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddSecurityGroupParamsWithTimeout creates a new AddSecurityGroupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddSecurityGroupParamsWithTimeout(timeout time.Duration) *AddSecurityGroupParams {
	var ()
	return &AddSecurityGroupParams{

		timeout: timeout,
	}
}

// NewAddSecurityGroupParamsWithContext creates a new AddSecurityGroupParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddSecurityGroupParamsWithContext(ctx context.Context) *AddSecurityGroupParams {
	var ()
	return &AddSecurityGroupParams{

		Context: ctx,
	}
}

// NewAddSecurityGroupParamsWithHTTPClient creates a new AddSecurityGroupParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddSecurityGroupParamsWithHTTPClient(client *http.Client) *AddSecurityGroupParams {
	var ()
	return &AddSecurityGroupParams{
		HTTPClient: client,
	}
}

/*AddSecurityGroupParams contains all the parameters to send to the API endpoint
for the add security group operation typically these are written to a http.Request
*/
type AddSecurityGroupParams struct {

	/*ID
	  The SecurityGroup ID

	*/
	ID string
	/*InstanceID
	  The EC2 Instance ID

	*/
	InstanceID *string
	/*NetworkInterfaceID
	  The EC2 Network Interface ID

	*/
	NetworkInterfaceID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add security group params
func (o *AddSecurityGroupParams) WithTimeout(timeout time.Duration) *AddSecurityGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add security group params
func (o *AddSecurityGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add security group params
func (o *AddSecurityGroupParams) WithContext(ctx context.Context) *AddSecurityGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add security group params
func (o *AddSecurityGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add security group params
func (o *AddSecurityGroupParams) WithHTTPClient(client *http.Client) *AddSecurityGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add security group params
func (o *AddSecurityGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the add security group params
func (o *AddSecurityGroupParams) WithID(id string) *AddSecurityGroupParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the add security group params
func (o *AddSecurityGroupParams) SetID(id string) {
	o.ID = id
}

// WithInstanceID adds the instanceID to the add security group params
func (o *AddSecurityGroupParams) WithInstanceID(instanceID *string) *AddSecurityGroupParams {
	o.SetInstanceID(instanceID)
	return o
}

// SetInstanceID adds the instanceId to the add security group params
func (o *AddSecurityGroupParams) SetInstanceID(instanceID *string) {
	o.InstanceID = instanceID
}

// WithNetworkInterfaceID adds the networkInterfaceID to the add security group params
func (o *AddSecurityGroupParams) WithNetworkInterfaceID(networkInterfaceID *string) *AddSecurityGroupParams {
	o.SetNetworkInterfaceID(networkInterfaceID)
	return o
}

// SetNetworkInterfaceID adds the networkInterfaceId to the add security group params
func (o *AddSecurityGroupParams) SetNetworkInterfaceID(networkInterfaceID *string) {
	o.NetworkInterfaceID = networkInterfaceID
}

// WriteToRequest writes these params to a swagger request
func (o *AddSecurityGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.InstanceID != nil {

		// query param instance_id
		var qrInstanceID string
		if o.InstanceID != nil {
			qrInstanceID = *o.InstanceID
		}
		qInstanceID := qrInstanceID
		if qInstanceID != "" {
			if err := r.SetQueryParam("instance_id", qInstanceID); err != nil {
				return err
			}
		}

	}

	if o.NetworkInterfaceID != nil {

		// query param network_interface_id
		var qrNetworkInterfaceID string
		if o.NetworkInterfaceID != nil {
			qrNetworkInterfaceID = *o.NetworkInterfaceID
		}
		qNetworkInterfaceID := qrNetworkInterfaceID
		if qNetworkInterfaceID != "" {
			if err := r.SetQueryParam("network_interface_id", qNetworkInterfaceID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
