// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"quortex.io/kubestitute/clients/ec2adapter/models"
)

// AuthorizeSecurityGroupEgressReader is a Reader for the AuthorizeSecurityGroupEgress structure.
type AuthorizeSecurityGroupEgressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AuthorizeSecurityGroupEgressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAuthorizeSecurityGroupEgressCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAuthorizeSecurityGroupEgressBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAuthorizeSecurityGroupEgressForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAuthorizeSecurityGroupEgressNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAuthorizeSecurityGroupEgressInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAuthorizeSecurityGroupEgressCreated creates a AuthorizeSecurityGroupEgressCreated with default headers values
func NewAuthorizeSecurityGroupEgressCreated() *AuthorizeSecurityGroupEgressCreated {
	return &AuthorizeSecurityGroupEgressCreated{}
}

/*
AuthorizeSecurityGroupEgressCreated handles this case with default header values.

Created
*/
type AuthorizeSecurityGroupEgressCreated struct {
	Payload *models.SecurityGroup
}

func (o *AuthorizeSecurityGroupEgressCreated) Error() string {
	return fmt.Sprintf("[POST /security-groups/{id}/egress][%d] authorizeSecurityGroupEgressCreated  %+v", 201, o.Payload)
}

func (o *AuthorizeSecurityGroupEgressCreated) GetPayload() *models.SecurityGroup {
	return o.Payload
}

func (o *AuthorizeSecurityGroupEgressCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SecurityGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAuthorizeSecurityGroupEgressBadRequest creates a AuthorizeSecurityGroupEgressBadRequest with default headers values
func NewAuthorizeSecurityGroupEgressBadRequest() *AuthorizeSecurityGroupEgressBadRequest {
	return &AuthorizeSecurityGroupEgressBadRequest{}
}

/*
AuthorizeSecurityGroupEgressBadRequest handles this case with default header values.

Bad Request
*/
type AuthorizeSecurityGroupEgressBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *AuthorizeSecurityGroupEgressBadRequest) Error() string {
	return fmt.Sprintf("[POST /security-groups/{id}/egress][%d] authorizeSecurityGroupEgressBadRequest  %+v", 400, o.Payload)
}

func (o *AuthorizeSecurityGroupEgressBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *AuthorizeSecurityGroupEgressBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAuthorizeSecurityGroupEgressForbidden creates a AuthorizeSecurityGroupEgressForbidden with default headers values
func NewAuthorizeSecurityGroupEgressForbidden() *AuthorizeSecurityGroupEgressForbidden {
	return &AuthorizeSecurityGroupEgressForbidden{}
}

/*
AuthorizeSecurityGroupEgressForbidden handles this case with default header values.

Forbidden
*/
type AuthorizeSecurityGroupEgressForbidden struct {
	Payload *models.ErrorResponse
}

func (o *AuthorizeSecurityGroupEgressForbidden) Error() string {
	return fmt.Sprintf("[POST /security-groups/{id}/egress][%d] authorizeSecurityGroupEgressForbidden  %+v", 403, o.Payload)
}

func (o *AuthorizeSecurityGroupEgressForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *AuthorizeSecurityGroupEgressForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAuthorizeSecurityGroupEgressNotFound creates a AuthorizeSecurityGroupEgressNotFound with default headers values
func NewAuthorizeSecurityGroupEgressNotFound() *AuthorizeSecurityGroupEgressNotFound {
	return &AuthorizeSecurityGroupEgressNotFound{}
}

/*
AuthorizeSecurityGroupEgressNotFound handles this case with default header values.

Not Found
*/
type AuthorizeSecurityGroupEgressNotFound struct {
	Payload *models.ErrorResponse
}

func (o *AuthorizeSecurityGroupEgressNotFound) Error() string {
	return fmt.Sprintf("[POST /security-groups/{id}/egress][%d] authorizeSecurityGroupEgressNotFound  %+v", 404, o.Payload)
}

func (o *AuthorizeSecurityGroupEgressNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *AuthorizeSecurityGroupEgressNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAuthorizeSecurityGroupEgressInternalServerError creates a AuthorizeSecurityGroupEgressInternalServerError with default headers values
func NewAuthorizeSecurityGroupEgressInternalServerError() *AuthorizeSecurityGroupEgressInternalServerError {
	return &AuthorizeSecurityGroupEgressInternalServerError{}
}

/*
AuthorizeSecurityGroupEgressInternalServerError handles this case with default header values.

Internal Server Error
*/
type AuthorizeSecurityGroupEgressInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *AuthorizeSecurityGroupEgressInternalServerError) Error() string {
	return fmt.Sprintf("[POST /security-groups/{id}/egress][%d] authorizeSecurityGroupEgressInternalServerError  %+v", 500, o.Payload)
}

func (o *AuthorizeSecurityGroupEgressInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *AuthorizeSecurityGroupEgressInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
