// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"quortex.io/kubestitute/clients/ec2adapter/models"
)

// NewAuthorizeSecurityGroupEgressParams creates a new AuthorizeSecurityGroupEgressParams object
// with the default values initialized.
func NewAuthorizeSecurityGroupEgressParams() *AuthorizeSecurityGroupEgressParams {
	var ()
	return &AuthorizeSecurityGroupEgressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAuthorizeSecurityGroupEgressParamsWithTimeout creates a new AuthorizeSecurityGroupEgressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAuthorizeSecurityGroupEgressParamsWithTimeout(timeout time.Duration) *AuthorizeSecurityGroupEgressParams {
	var ()
	return &AuthorizeSecurityGroupEgressParams{

		timeout: timeout,
	}
}

// NewAuthorizeSecurityGroupEgressParamsWithContext creates a new AuthorizeSecurityGroupEgressParams object
// with the default values initialized, and the ability to set a context for a request
func NewAuthorizeSecurityGroupEgressParamsWithContext(ctx context.Context) *AuthorizeSecurityGroupEgressParams {
	var ()
	return &AuthorizeSecurityGroupEgressParams{

		Context: ctx,
	}
}

// NewAuthorizeSecurityGroupEgressParamsWithHTTPClient creates a new AuthorizeSecurityGroupEgressParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAuthorizeSecurityGroupEgressParamsWithHTTPClient(client *http.Client) *AuthorizeSecurityGroupEgressParams {
	var ()
	return &AuthorizeSecurityGroupEgressParams{
		HTTPClient: client,
	}
}

/*AuthorizeSecurityGroupEgressParams contains all the parameters to send to the API endpoint
for the authorize security group egress operation typically these are written to a http.Request
*/
type AuthorizeSecurityGroupEgressParams struct {

	/*ID
	  The SecurityGroup ID

	*/
	ID string
	/*Request
	  The SecurityGroup Permission request

	*/
	Request *models.SecurityGroupPermissionRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the authorize security group egress params
func (o *AuthorizeSecurityGroupEgressParams) WithTimeout(timeout time.Duration) *AuthorizeSecurityGroupEgressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the authorize security group egress params
func (o *AuthorizeSecurityGroupEgressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the authorize security group egress params
func (o *AuthorizeSecurityGroupEgressParams) WithContext(ctx context.Context) *AuthorizeSecurityGroupEgressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the authorize security group egress params
func (o *AuthorizeSecurityGroupEgressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the authorize security group egress params
func (o *AuthorizeSecurityGroupEgressParams) WithHTTPClient(client *http.Client) *AuthorizeSecurityGroupEgressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the authorize security group egress params
func (o *AuthorizeSecurityGroupEgressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the authorize security group egress params
func (o *AuthorizeSecurityGroupEgressParams) WithID(id string) *AuthorizeSecurityGroupEgressParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the authorize security group egress params
func (o *AuthorizeSecurityGroupEgressParams) SetID(id string) {
	o.ID = id
}

// WithRequest adds the request to the authorize security group egress params
func (o *AuthorizeSecurityGroupEgressParams) WithRequest(request *models.SecurityGroupPermissionRequest) *AuthorizeSecurityGroupEgressParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the authorize security group egress params
func (o *AuthorizeSecurityGroupEgressParams) SetRequest(request *models.SecurityGroupPermissionRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *AuthorizeSecurityGroupEgressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
