// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"quortex.io/kubestitute/clients/ec2adapter/models"
)

// NewAuthorizeSecurityGroupIngressParams creates a new AuthorizeSecurityGroupIngressParams object
// with the default values initialized.
func NewAuthorizeSecurityGroupIngressParams() *AuthorizeSecurityGroupIngressParams {
	var ()
	return &AuthorizeSecurityGroupIngressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAuthorizeSecurityGroupIngressParamsWithTimeout creates a new AuthorizeSecurityGroupIngressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAuthorizeSecurityGroupIngressParamsWithTimeout(timeout time.Duration) *AuthorizeSecurityGroupIngressParams {
	var ()
	return &AuthorizeSecurityGroupIngressParams{

		timeout: timeout,
	}
}

// NewAuthorizeSecurityGroupIngressParamsWithContext creates a new AuthorizeSecurityGroupIngressParams object
// with the default values initialized, and the ability to set a context for a request
func NewAuthorizeSecurityGroupIngressParamsWithContext(ctx context.Context) *AuthorizeSecurityGroupIngressParams {
	var ()
	return &AuthorizeSecurityGroupIngressParams{

		Context: ctx,
	}
}

// NewAuthorizeSecurityGroupIngressParamsWithHTTPClient creates a new AuthorizeSecurityGroupIngressParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAuthorizeSecurityGroupIngressParamsWithHTTPClient(client *http.Client) *AuthorizeSecurityGroupIngressParams {
	var ()
	return &AuthorizeSecurityGroupIngressParams{
		HTTPClient: client,
	}
}

/*
AuthorizeSecurityGroupIngressParams contains all the parameters to send to the API endpoint
for the authorize security group ingress operation typically these are written to a http.Request
*/
type AuthorizeSecurityGroupIngressParams struct {

	/*ID
	  The SecurityGroup ID

	*/
	ID string
	/*Request
	  The SecurityGroup Permission request

	*/
	Request *models.SecurityGroupPermissionRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the authorize security group ingress params
func (o *AuthorizeSecurityGroupIngressParams) WithTimeout(timeout time.Duration) *AuthorizeSecurityGroupIngressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the authorize security group ingress params
func (o *AuthorizeSecurityGroupIngressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the authorize security group ingress params
func (o *AuthorizeSecurityGroupIngressParams) WithContext(ctx context.Context) *AuthorizeSecurityGroupIngressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the authorize security group ingress params
func (o *AuthorizeSecurityGroupIngressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the authorize security group ingress params
func (o *AuthorizeSecurityGroupIngressParams) WithHTTPClient(client *http.Client) *AuthorizeSecurityGroupIngressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the authorize security group ingress params
func (o *AuthorizeSecurityGroupIngressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the authorize security group ingress params
func (o *AuthorizeSecurityGroupIngressParams) WithID(id string) *AuthorizeSecurityGroupIngressParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the authorize security group ingress params
func (o *AuthorizeSecurityGroupIngressParams) SetID(id string) {
	o.ID = id
}

// WithRequest adds the request to the authorize security group ingress params
func (o *AuthorizeSecurityGroupIngressParams) WithRequest(request *models.SecurityGroupPermissionRequest) *AuthorizeSecurityGroupIngressParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the authorize security group ingress params
func (o *AuthorizeSecurityGroupIngressParams) SetRequest(request *models.SecurityGroupPermissionRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *AuthorizeSecurityGroupIngressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
