// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateAddressParams creates a new CreateAddressParams object
// with the default values initialized.
func NewCreateAddressParams() *CreateAddressParams {

	return &CreateAddressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAddressParamsWithTimeout creates a new CreateAddressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateAddressParamsWithTimeout(timeout time.Duration) *CreateAddressParams {

	return &CreateAddressParams{

		timeout: timeout,
	}
}

// NewCreateAddressParamsWithContext creates a new CreateAddressParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateAddressParamsWithContext(ctx context.Context) *CreateAddressParams {

	return &CreateAddressParams{

		Context: ctx,
	}
}

// NewCreateAddressParamsWithHTTPClient creates a new CreateAddressParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateAddressParamsWithHTTPClient(client *http.Client) *CreateAddressParams {

	return &CreateAddressParams{
		HTTPClient: client,
	}
}

/*
CreateAddressParams contains all the parameters to send to the API endpoint
for the create address operation typically these are written to a http.Request
*/
type CreateAddressParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create address params
func (o *CreateAddressParams) WithTimeout(timeout time.Duration) *CreateAddressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create address params
func (o *CreateAddressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create address params
func (o *CreateAddressParams) WithContext(ctx context.Context) *CreateAddressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create address params
func (o *CreateAddressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create address params
func (o *CreateAddressParams) WithHTTPClient(client *http.Client) *CreateAddressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create address params
func (o *CreateAddressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAddressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
