// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"quortex.io/kubestitute/clients/ec2adapter/models"
)

// NewCreateSecurityGroupParams creates a new CreateSecurityGroupParams object
// with the default values initialized.
func NewCreateSecurityGroupParams() *CreateSecurityGroupParams {
	var ()
	return &CreateSecurityGroupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSecurityGroupParamsWithTimeout creates a new CreateSecurityGroupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateSecurityGroupParamsWithTimeout(timeout time.Duration) *CreateSecurityGroupParams {
	var ()
	return &CreateSecurityGroupParams{

		timeout: timeout,
	}
}

// NewCreateSecurityGroupParamsWithContext creates a new CreateSecurityGroupParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateSecurityGroupParamsWithContext(ctx context.Context) *CreateSecurityGroupParams {
	var ()
	return &CreateSecurityGroupParams{

		Context: ctx,
	}
}

// NewCreateSecurityGroupParamsWithHTTPClient creates a new CreateSecurityGroupParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateSecurityGroupParamsWithHTTPClient(client *http.Client) *CreateSecurityGroupParams {
	var ()
	return &CreateSecurityGroupParams{
		HTTPClient: client,
	}
}

/*
CreateSecurityGroupParams contains all the parameters to send to the API endpoint
for the create security group operation typically these are written to a http.Request
*/
type CreateSecurityGroupParams struct {

	/*Request
	  The SecurityGroup request

	*/
	Request *models.CreateSecurityGroupRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create security group params
func (o *CreateSecurityGroupParams) WithTimeout(timeout time.Duration) *CreateSecurityGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create security group params
func (o *CreateSecurityGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create security group params
func (o *CreateSecurityGroupParams) WithContext(ctx context.Context) *CreateSecurityGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create security group params
func (o *CreateSecurityGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create security group params
func (o *CreateSecurityGroupParams) WithHTTPClient(client *http.Client) *CreateSecurityGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create security group params
func (o *CreateSecurityGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the create security group params
func (o *CreateSecurityGroupParams) WithRequest(request *models.CreateSecurityGroupRequest) *CreateSecurityGroupParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the create security group params
func (o *CreateSecurityGroupParams) SetRequest(request *models.CreateSecurityGroupRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSecurityGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
