// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"quortex.io/kubestitute/clients/ec2adapter/models"
)

// CreateSecurityGroupReader is a Reader for the CreateSecurityGroup structure.
type CreateSecurityGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSecurityGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateSecurityGroupCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateSecurityGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateSecurityGroupForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateSecurityGroupConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateSecurityGroupInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateSecurityGroupCreated creates a CreateSecurityGroupCreated with default headers values
func NewCreateSecurityGroupCreated() *CreateSecurityGroupCreated {
	return &CreateSecurityGroupCreated{}
}

/*CreateSecurityGroupCreated handles this case with default header values.

Created
*/
type CreateSecurityGroupCreated struct {
	Payload *models.SecurityGroup
}

func (o *CreateSecurityGroupCreated) Error() string {
	return fmt.Sprintf("[POST /security-groups][%d] createSecurityGroupCreated  %+v", 201, o.Payload)
}

func (o *CreateSecurityGroupCreated) GetPayload() *models.SecurityGroup {
	return o.Payload
}

func (o *CreateSecurityGroupCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SecurityGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSecurityGroupBadRequest creates a CreateSecurityGroupBadRequest with default headers values
func NewCreateSecurityGroupBadRequest() *CreateSecurityGroupBadRequest {
	return &CreateSecurityGroupBadRequest{}
}

/*CreateSecurityGroupBadRequest handles this case with default header values.

Bad Request
*/
type CreateSecurityGroupBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *CreateSecurityGroupBadRequest) Error() string {
	return fmt.Sprintf("[POST /security-groups][%d] createSecurityGroupBadRequest  %+v", 400, o.Payload)
}

func (o *CreateSecurityGroupBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateSecurityGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSecurityGroupForbidden creates a CreateSecurityGroupForbidden with default headers values
func NewCreateSecurityGroupForbidden() *CreateSecurityGroupForbidden {
	return &CreateSecurityGroupForbidden{}
}

/*CreateSecurityGroupForbidden handles this case with default header values.

Forbidden
*/
type CreateSecurityGroupForbidden struct {
	Payload *models.ErrorResponse
}

func (o *CreateSecurityGroupForbidden) Error() string {
	return fmt.Sprintf("[POST /security-groups][%d] createSecurityGroupForbidden  %+v", 403, o.Payload)
}

func (o *CreateSecurityGroupForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateSecurityGroupForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSecurityGroupConflict creates a CreateSecurityGroupConflict with default headers values
func NewCreateSecurityGroupConflict() *CreateSecurityGroupConflict {
	return &CreateSecurityGroupConflict{}
}

/*CreateSecurityGroupConflict handles this case with default header values.

Conflict
*/
type CreateSecurityGroupConflict struct {
	Payload *models.ErrorResponse
}

func (o *CreateSecurityGroupConflict) Error() string {
	return fmt.Sprintf("[POST /security-groups][%d] createSecurityGroupConflict  %+v", 409, o.Payload)
}

func (o *CreateSecurityGroupConflict) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateSecurityGroupConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSecurityGroupInternalServerError creates a CreateSecurityGroupInternalServerError with default headers values
func NewCreateSecurityGroupInternalServerError() *CreateSecurityGroupInternalServerError {
	return &CreateSecurityGroupInternalServerError{}
}

/*CreateSecurityGroupInternalServerError handles this case with default header values.

Internal Server Error
*/
type CreateSecurityGroupInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *CreateSecurityGroupInternalServerError) Error() string {
	return fmt.Sprintf("[POST /security-groups][%d] createSecurityGroupInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateSecurityGroupInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateSecurityGroupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
