// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"quortex.io/kubestitute/clients/ec2adapter/models"
)

// DeleteSecurityGroupsReader is a Reader for the DeleteSecurityGroups structure.
type DeleteSecurityGroupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSecurityGroupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteSecurityGroupsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteSecurityGroupsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteSecurityGroupsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteSecurityGroupsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteSecurityGroupsNoContent creates a DeleteSecurityGroupsNoContent with default headers values
func NewDeleteSecurityGroupsNoContent() *DeleteSecurityGroupsNoContent {
	return &DeleteSecurityGroupsNoContent{}
}

/*
DeleteSecurityGroupsNoContent handles this case with default header values.

No Content
*/
type DeleteSecurityGroupsNoContent struct {
	Payload string
}

func (o *DeleteSecurityGroupsNoContent) Error() string {
	return fmt.Sprintf("[DELETE /security-groups][%d] deleteSecurityGroupsNoContent  %+v", 204, o.Payload)
}

func (o *DeleteSecurityGroupsNoContent) GetPayload() string {
	return o.Payload
}

func (o *DeleteSecurityGroupsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSecurityGroupsBadRequest creates a DeleteSecurityGroupsBadRequest with default headers values
func NewDeleteSecurityGroupsBadRequest() *DeleteSecurityGroupsBadRequest {
	return &DeleteSecurityGroupsBadRequest{}
}

/*
DeleteSecurityGroupsBadRequest handles this case with default header values.

Bad Request
*/
type DeleteSecurityGroupsBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *DeleteSecurityGroupsBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /security-groups][%d] deleteSecurityGroupsBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteSecurityGroupsBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteSecurityGroupsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSecurityGroupsForbidden creates a DeleteSecurityGroupsForbidden with default headers values
func NewDeleteSecurityGroupsForbidden() *DeleteSecurityGroupsForbidden {
	return &DeleteSecurityGroupsForbidden{}
}

/*
DeleteSecurityGroupsForbidden handles this case with default header values.

Forbidden
*/
type DeleteSecurityGroupsForbidden struct {
	Payload *models.ErrorResponse
}

func (o *DeleteSecurityGroupsForbidden) Error() string {
	return fmt.Sprintf("[DELETE /security-groups][%d] deleteSecurityGroupsForbidden  %+v", 403, o.Payload)
}

func (o *DeleteSecurityGroupsForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteSecurityGroupsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSecurityGroupsInternalServerError creates a DeleteSecurityGroupsInternalServerError with default headers values
func NewDeleteSecurityGroupsInternalServerError() *DeleteSecurityGroupsInternalServerError {
	return &DeleteSecurityGroupsInternalServerError{}
}

/*
DeleteSecurityGroupsInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteSecurityGroupsInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *DeleteSecurityGroupsInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /security-groups][%d] deleteSecurityGroupsInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteSecurityGroupsInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteSecurityGroupsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
