// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAddressParams creates a new DeleteAddressParams object
// with the default values initialized.
func NewDeleteAddressParams() *DeleteAddressParams {
	var ()
	return &DeleteAddressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAddressParamsWithTimeout creates a new DeleteAddressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAddressParamsWithTimeout(timeout time.Duration) *DeleteAddressParams {
	var ()
	return &DeleteAddressParams{

		timeout: timeout,
	}
}

// NewDeleteAddressParamsWithContext creates a new DeleteAddressParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAddressParamsWithContext(ctx context.Context) *DeleteAddressParams {
	var ()
	return &DeleteAddressParams{

		Context: ctx,
	}
}

// NewDeleteAddressParamsWithHTTPClient creates a new DeleteAddressParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAddressParamsWithHTTPClient(client *http.Client) *DeleteAddressParams {
	var ()
	return &DeleteAddressParams{
		HTTPClient: client,
	}
}

/*
DeleteAddressParams contains all the parameters to send to the API endpoint
for the delete address operation typically these are written to a http.Request
*/
type DeleteAddressParams struct {

	/*ID
	  The ElasticIP Allocation ID

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete address params
func (o *DeleteAddressParams) WithTimeout(timeout time.Duration) *DeleteAddressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete address params
func (o *DeleteAddressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete address params
func (o *DeleteAddressParams) WithContext(ctx context.Context) *DeleteAddressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete address params
func (o *DeleteAddressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete address params
func (o *DeleteAddressParams) WithHTTPClient(client *http.Client) *DeleteAddressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete address params
func (o *DeleteAddressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete address params
func (o *DeleteAddressParams) WithID(id string) *DeleteAddressParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete address params
func (o *DeleteAddressParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAddressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
