// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteSecurityGroupsParams creates a new DeleteSecurityGroupsParams object
// with the default values initialized.
func NewDeleteSecurityGroupsParams() *DeleteSecurityGroupsParams {

	return &DeleteSecurityGroupsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSecurityGroupsParamsWithTimeout creates a new DeleteSecurityGroupsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSecurityGroupsParamsWithTimeout(timeout time.Duration) *DeleteSecurityGroupsParams {

	return &DeleteSecurityGroupsParams{

		timeout: timeout,
	}
}

// NewDeleteSecurityGroupsParamsWithContext creates a new DeleteSecurityGroupsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSecurityGroupsParamsWithContext(ctx context.Context) *DeleteSecurityGroupsParams {

	return &DeleteSecurityGroupsParams{

		Context: ctx,
	}
}

// NewDeleteSecurityGroupsParamsWithHTTPClient creates a new DeleteSecurityGroupsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSecurityGroupsParamsWithHTTPClient(client *http.Client) *DeleteSecurityGroupsParams {

	return &DeleteSecurityGroupsParams{
		HTTPClient: client,
	}
}

/*DeleteSecurityGroupsParams contains all the parameters to send to the API endpoint
for the delete security groups operation typically these are written to a http.Request
*/
type DeleteSecurityGroupsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete security groups params
func (o *DeleteSecurityGroupsParams) WithTimeout(timeout time.Duration) *DeleteSecurityGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete security groups params
func (o *DeleteSecurityGroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete security groups params
func (o *DeleteSecurityGroupsParams) WithContext(ctx context.Context) *DeleteSecurityGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete security groups params
func (o *DeleteSecurityGroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete security groups params
func (o *DeleteSecurityGroupsParams) WithHTTPClient(client *http.Client) *DeleteSecurityGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete security groups params
func (o *DeleteSecurityGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSecurityGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
