// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"quortex.io/kubestitute/clients/ec2adapter/models"
)

// DeleteAddressesReader is a Reader for the DeleteAddresses structure.
type DeleteAddressesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAddressesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAddressesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteAddressesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteAddressesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteAddressesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAddressesNoContent creates a DeleteAddressesNoContent with default headers values
func NewDeleteAddressesNoContent() *DeleteAddressesNoContent {
	return &DeleteAddressesNoContent{}
}

/*
DeleteAddressesNoContent handles this case with default header values.

No Content
*/
type DeleteAddressesNoContent struct {
	Payload string
}

func (o *DeleteAddressesNoContent) Error() string {
	return fmt.Sprintf("[DELETE /addresses][%d] deleteAddressesNoContent  %+v", 204, o.Payload)
}

func (o *DeleteAddressesNoContent) GetPayload() string {
	return o.Payload
}

func (o *DeleteAddressesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAddressesBadRequest creates a DeleteAddressesBadRequest with default headers values
func NewDeleteAddressesBadRequest() *DeleteAddressesBadRequest {
	return &DeleteAddressesBadRequest{}
}

/*
DeleteAddressesBadRequest handles this case with default header values.

Bad Request
*/
type DeleteAddressesBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *DeleteAddressesBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /addresses][%d] deleteAddressesBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteAddressesBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteAddressesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAddressesForbidden creates a DeleteAddressesForbidden with default headers values
func NewDeleteAddressesForbidden() *DeleteAddressesForbidden {
	return &DeleteAddressesForbidden{}
}

/*
DeleteAddressesForbidden handles this case with default header values.

Forbidden
*/
type DeleteAddressesForbidden struct {
	Payload *models.ErrorResponse
}

func (o *DeleteAddressesForbidden) Error() string {
	return fmt.Sprintf("[DELETE /addresses][%d] deleteAddressesForbidden  %+v", 403, o.Payload)
}

func (o *DeleteAddressesForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteAddressesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAddressesInternalServerError creates a DeleteAddressesInternalServerError with default headers values
func NewDeleteAddressesInternalServerError() *DeleteAddressesInternalServerError {
	return &DeleteAddressesInternalServerError{}
}

/*
DeleteAddressesInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteAddressesInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *DeleteAddressesInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /addresses][%d] deleteAddressesInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteAddressesInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteAddressesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
