// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"quortex.io/kubestitute/clients/ec2adapter/models"
)

// DetachAutoscalingGroupInstancesReader is a Reader for the DetachAutoscalingGroupInstances structure.
type DetachAutoscalingGroupInstancesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DetachAutoscalingGroupInstancesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDetachAutoscalingGroupInstancesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDetachAutoscalingGroupInstancesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDetachAutoscalingGroupInstancesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDetachAutoscalingGroupInstancesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDetachAutoscalingGroupInstancesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDetachAutoscalingGroupInstancesNoContent creates a DetachAutoscalingGroupInstancesNoContent with default headers values
func NewDetachAutoscalingGroupInstancesNoContent() *DetachAutoscalingGroupInstancesNoContent {
	return &DetachAutoscalingGroupInstancesNoContent{}
}

/*
DetachAutoscalingGroupInstancesNoContent handles this case with default header values.

No Content
*/
type DetachAutoscalingGroupInstancesNoContent struct {
	Payload string
}

func (o *DetachAutoscalingGroupInstancesNoContent) Error() string {
	return fmt.Sprintf("[DELETE /autoscaling-groups/{name}/instances][%d] detachAutoscalingGroupInstancesNoContent  %+v", 204, o.Payload)
}

func (o *DetachAutoscalingGroupInstancesNoContent) GetPayload() string {
	return o.Payload
}

func (o *DetachAutoscalingGroupInstancesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetachAutoscalingGroupInstancesBadRequest creates a DetachAutoscalingGroupInstancesBadRequest with default headers values
func NewDetachAutoscalingGroupInstancesBadRequest() *DetachAutoscalingGroupInstancesBadRequest {
	return &DetachAutoscalingGroupInstancesBadRequest{}
}

/*
DetachAutoscalingGroupInstancesBadRequest handles this case with default header values.

Bad Request
*/
type DetachAutoscalingGroupInstancesBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *DetachAutoscalingGroupInstancesBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /autoscaling-groups/{name}/instances][%d] detachAutoscalingGroupInstancesBadRequest  %+v", 400, o.Payload)
}

func (o *DetachAutoscalingGroupInstancesBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DetachAutoscalingGroupInstancesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetachAutoscalingGroupInstancesForbidden creates a DetachAutoscalingGroupInstancesForbidden with default headers values
func NewDetachAutoscalingGroupInstancesForbidden() *DetachAutoscalingGroupInstancesForbidden {
	return &DetachAutoscalingGroupInstancesForbidden{}
}

/*
DetachAutoscalingGroupInstancesForbidden handles this case with default header values.

Forbidden
*/
type DetachAutoscalingGroupInstancesForbidden struct {
	Payload *models.ErrorResponse
}

func (o *DetachAutoscalingGroupInstancesForbidden) Error() string {
	return fmt.Sprintf("[DELETE /autoscaling-groups/{name}/instances][%d] detachAutoscalingGroupInstancesForbidden  %+v", 403, o.Payload)
}

func (o *DetachAutoscalingGroupInstancesForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DetachAutoscalingGroupInstancesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetachAutoscalingGroupInstancesNotFound creates a DetachAutoscalingGroupInstancesNotFound with default headers values
func NewDetachAutoscalingGroupInstancesNotFound() *DetachAutoscalingGroupInstancesNotFound {
	return &DetachAutoscalingGroupInstancesNotFound{}
}

/*
DetachAutoscalingGroupInstancesNotFound handles this case with default header values.

Not Found
*/
type DetachAutoscalingGroupInstancesNotFound struct {
	Payload *models.ErrorResponse
}

func (o *DetachAutoscalingGroupInstancesNotFound) Error() string {
	return fmt.Sprintf("[DELETE /autoscaling-groups/{name}/instances][%d] detachAutoscalingGroupInstancesNotFound  %+v", 404, o.Payload)
}

func (o *DetachAutoscalingGroupInstancesNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DetachAutoscalingGroupInstancesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetachAutoscalingGroupInstancesInternalServerError creates a DetachAutoscalingGroupInstancesInternalServerError with default headers values
func NewDetachAutoscalingGroupInstancesInternalServerError() *DetachAutoscalingGroupInstancesInternalServerError {
	return &DetachAutoscalingGroupInstancesInternalServerError{}
}

/*
DetachAutoscalingGroupInstancesInternalServerError handles this case with default header values.

Internal Server Error
*/
type DetachAutoscalingGroupInstancesInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *DetachAutoscalingGroupInstancesInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /autoscaling-groups/{name}/instances][%d] detachAutoscalingGroupInstancesInternalServerError  %+v", 500, o.Payload)
}

func (o *DetachAutoscalingGroupInstancesInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DetachAutoscalingGroupInstancesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
