// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"quortex.io/kubestitute/clients/ec2adapter/models"
)

// DisassociateAddressReader is a Reader for the DisassociateAddress structure.
type DisassociateAddressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DisassociateAddressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDisassociateAddressNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDisassociateAddressBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDisassociateAddressForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDisassociateAddressNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDisassociateAddressInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDisassociateAddressNoContent creates a DisassociateAddressNoContent with default headers values
func NewDisassociateAddressNoContent() *DisassociateAddressNoContent {
	return &DisassociateAddressNoContent{}
}

/*DisassociateAddressNoContent handles this case with default header values.

No Content
*/
type DisassociateAddressNoContent struct {
	Payload string
}

func (o *DisassociateAddressNoContent) Error() string {
	return fmt.Sprintf("[DELETE /addresses/{id}/associate][%d] disassociateAddressNoContent  %+v", 204, o.Payload)
}

func (o *DisassociateAddressNoContent) GetPayload() string {
	return o.Payload
}

func (o *DisassociateAddressNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisassociateAddressBadRequest creates a DisassociateAddressBadRequest with default headers values
func NewDisassociateAddressBadRequest() *DisassociateAddressBadRequest {
	return &DisassociateAddressBadRequest{}
}

/*DisassociateAddressBadRequest handles this case with default header values.

Bad Request
*/
type DisassociateAddressBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *DisassociateAddressBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /addresses/{id}/associate][%d] disassociateAddressBadRequest  %+v", 400, o.Payload)
}

func (o *DisassociateAddressBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DisassociateAddressBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisassociateAddressForbidden creates a DisassociateAddressForbidden with default headers values
func NewDisassociateAddressForbidden() *DisassociateAddressForbidden {
	return &DisassociateAddressForbidden{}
}

/*DisassociateAddressForbidden handles this case with default header values.

Forbidden
*/
type DisassociateAddressForbidden struct {
	Payload *models.ErrorResponse
}

func (o *DisassociateAddressForbidden) Error() string {
	return fmt.Sprintf("[DELETE /addresses/{id}/associate][%d] disassociateAddressForbidden  %+v", 403, o.Payload)
}

func (o *DisassociateAddressForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DisassociateAddressForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisassociateAddressNotFound creates a DisassociateAddressNotFound with default headers values
func NewDisassociateAddressNotFound() *DisassociateAddressNotFound {
	return &DisassociateAddressNotFound{}
}

/*DisassociateAddressNotFound handles this case with default header values.

Not Found
*/
type DisassociateAddressNotFound struct {
	Payload *models.ErrorResponse
}

func (o *DisassociateAddressNotFound) Error() string {
	return fmt.Sprintf("[DELETE /addresses/{id}/associate][%d] disassociateAddressNotFound  %+v", 404, o.Payload)
}

func (o *DisassociateAddressNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DisassociateAddressNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDisassociateAddressInternalServerError creates a DisassociateAddressInternalServerError with default headers values
func NewDisassociateAddressInternalServerError() *DisassociateAddressInternalServerError {
	return &DisassociateAddressInternalServerError{}
}

/*DisassociateAddressInternalServerError handles this case with default header values.

Internal Server Error
*/
type DisassociateAddressInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *DisassociateAddressInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /addresses/{id}/associate][%d] disassociateAddressInternalServerError  %+v", 500, o.Payload)
}

func (o *DisassociateAddressInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DisassociateAddressInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
