// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAutoscalingGroupParams creates a new GetAutoscalingGroupParams object
// with the default values initialized.
func NewGetAutoscalingGroupParams() *GetAutoscalingGroupParams {
	var ()
	return &GetAutoscalingGroupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAutoscalingGroupParamsWithTimeout creates a new GetAutoscalingGroupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAutoscalingGroupParamsWithTimeout(timeout time.Duration) *GetAutoscalingGroupParams {
	var ()
	return &GetAutoscalingGroupParams{

		timeout: timeout,
	}
}

// NewGetAutoscalingGroupParamsWithContext creates a new GetAutoscalingGroupParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAutoscalingGroupParamsWithContext(ctx context.Context) *GetAutoscalingGroupParams {
	var ()
	return &GetAutoscalingGroupParams{

		Context: ctx,
	}
}

// NewGetAutoscalingGroupParamsWithHTTPClient creates a new GetAutoscalingGroupParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAutoscalingGroupParamsWithHTTPClient(client *http.Client) *GetAutoscalingGroupParams {
	var ()
	return &GetAutoscalingGroupParams{
		HTTPClient: client,
	}
}

/*GetAutoscalingGroupParams contains all the parameters to send to the API endpoint
for the get autoscaling group operation typically these are written to a http.Request
*/
type GetAutoscalingGroupParams struct {

	/*Name
	  The AutoscalingGroup name

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get autoscaling group params
func (o *GetAutoscalingGroupParams) WithTimeout(timeout time.Duration) *GetAutoscalingGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get autoscaling group params
func (o *GetAutoscalingGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get autoscaling group params
func (o *GetAutoscalingGroupParams) WithContext(ctx context.Context) *GetAutoscalingGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get autoscaling group params
func (o *GetAutoscalingGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get autoscaling group params
func (o *GetAutoscalingGroupParams) WithHTTPClient(client *http.Client) *GetAutoscalingGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get autoscaling group params
func (o *GetAutoscalingGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get autoscaling group params
func (o *GetAutoscalingGroupParams) WithName(name string) *GetAutoscalingGroupParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get autoscaling group params
func (o *GetAutoscalingGroupParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetAutoscalingGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
