// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"quortex.io/kubestitute/clients/ec2adapter/models"
)

// GetAutoscalingGroupReader is a Reader for the GetAutoscalingGroup structure.
type GetAutoscalingGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAutoscalingGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAutoscalingGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAutoscalingGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAutoscalingGroupForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAutoscalingGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAutoscalingGroupInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAutoscalingGroupOK creates a GetAutoscalingGroupOK with default headers values
func NewGetAutoscalingGroupOK() *GetAutoscalingGroupOK {
	return &GetAutoscalingGroupOK{}
}

/*
GetAutoscalingGroupOK handles this case with default header values.

OK
*/
type GetAutoscalingGroupOK struct {
	Payload *models.AutoscalingGroup
}

func (o *GetAutoscalingGroupOK) Error() string {
	return fmt.Sprintf("[GET /autoscaling-groups/{name}][%d] getAutoscalingGroupOK  %+v", 200, o.Payload)
}

func (o *GetAutoscalingGroupOK) GetPayload() *models.AutoscalingGroup {
	return o.Payload
}

func (o *GetAutoscalingGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AutoscalingGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAutoscalingGroupBadRequest creates a GetAutoscalingGroupBadRequest with default headers values
func NewGetAutoscalingGroupBadRequest() *GetAutoscalingGroupBadRequest {
	return &GetAutoscalingGroupBadRequest{}
}

/*
GetAutoscalingGroupBadRequest handles this case with default header values.

Bad Request
*/
type GetAutoscalingGroupBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *GetAutoscalingGroupBadRequest) Error() string {
	return fmt.Sprintf("[GET /autoscaling-groups/{name}][%d] getAutoscalingGroupBadRequest  %+v", 400, o.Payload)
}

func (o *GetAutoscalingGroupBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetAutoscalingGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAutoscalingGroupForbidden creates a GetAutoscalingGroupForbidden with default headers values
func NewGetAutoscalingGroupForbidden() *GetAutoscalingGroupForbidden {
	return &GetAutoscalingGroupForbidden{}
}

/*
GetAutoscalingGroupForbidden handles this case with default header values.

Forbidden
*/
type GetAutoscalingGroupForbidden struct {
	Payload *models.ErrorResponse
}

func (o *GetAutoscalingGroupForbidden) Error() string {
	return fmt.Sprintf("[GET /autoscaling-groups/{name}][%d] getAutoscalingGroupForbidden  %+v", 403, o.Payload)
}

func (o *GetAutoscalingGroupForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetAutoscalingGroupForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAutoscalingGroupNotFound creates a GetAutoscalingGroupNotFound with default headers values
func NewGetAutoscalingGroupNotFound() *GetAutoscalingGroupNotFound {
	return &GetAutoscalingGroupNotFound{}
}

/*
GetAutoscalingGroupNotFound handles this case with default header values.

Not Found
*/
type GetAutoscalingGroupNotFound struct {
	Payload *models.ErrorResponse
}

func (o *GetAutoscalingGroupNotFound) Error() string {
	return fmt.Sprintf("[GET /autoscaling-groups/{name}][%d] getAutoscalingGroupNotFound  %+v", 404, o.Payload)
}

func (o *GetAutoscalingGroupNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetAutoscalingGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAutoscalingGroupInternalServerError creates a GetAutoscalingGroupInternalServerError with default headers values
func NewGetAutoscalingGroupInternalServerError() *GetAutoscalingGroupInternalServerError {
	return &GetAutoscalingGroupInternalServerError{}
}

/*
GetAutoscalingGroupInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAutoscalingGroupInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *GetAutoscalingGroupInternalServerError) Error() string {
	return fmt.Sprintf("[GET /autoscaling-groups/{name}][%d] getAutoscalingGroupInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAutoscalingGroupInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetAutoscalingGroupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
