// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"quortex.io/kubestitute/clients/ec2adapter/models"
)

// GetSecurityGroupReader is a Reader for the GetSecurityGroup structure.
type GetSecurityGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSecurityGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSecurityGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetSecurityGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetSecurityGroupForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetSecurityGroupNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetSecurityGroupInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSecurityGroupOK creates a GetSecurityGroupOK with default headers values
func NewGetSecurityGroupOK() *GetSecurityGroupOK {
	return &GetSecurityGroupOK{}
}

/*
GetSecurityGroupOK handles this case with default header values.

OK
*/
type GetSecurityGroupOK struct {
	Payload *models.SecurityGroup
}

func (o *GetSecurityGroupOK) Error() string {
	return fmt.Sprintf("[GET /security-groups/{id}][%d] getSecurityGroupOK  %+v", 200, o.Payload)
}

func (o *GetSecurityGroupOK) GetPayload() *models.SecurityGroup {
	return o.Payload
}

func (o *GetSecurityGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SecurityGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSecurityGroupBadRequest creates a GetSecurityGroupBadRequest with default headers values
func NewGetSecurityGroupBadRequest() *GetSecurityGroupBadRequest {
	return &GetSecurityGroupBadRequest{}
}

/*
GetSecurityGroupBadRequest handles this case with default header values.

Bad Request
*/
type GetSecurityGroupBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *GetSecurityGroupBadRequest) Error() string {
	return fmt.Sprintf("[GET /security-groups/{id}][%d] getSecurityGroupBadRequest  %+v", 400, o.Payload)
}

func (o *GetSecurityGroupBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetSecurityGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSecurityGroupForbidden creates a GetSecurityGroupForbidden with default headers values
func NewGetSecurityGroupForbidden() *GetSecurityGroupForbidden {
	return &GetSecurityGroupForbidden{}
}

/*
GetSecurityGroupForbidden handles this case with default header values.

Forbidden
*/
type GetSecurityGroupForbidden struct {
	Payload *models.ErrorResponse
}

func (o *GetSecurityGroupForbidden) Error() string {
	return fmt.Sprintf("[GET /security-groups/{id}][%d] getSecurityGroupForbidden  %+v", 403, o.Payload)
}

func (o *GetSecurityGroupForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetSecurityGroupForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSecurityGroupNotFound creates a GetSecurityGroupNotFound with default headers values
func NewGetSecurityGroupNotFound() *GetSecurityGroupNotFound {
	return &GetSecurityGroupNotFound{}
}

/*
GetSecurityGroupNotFound handles this case with default header values.

Not Found
*/
type GetSecurityGroupNotFound struct {
	Payload *models.ErrorResponse
}

func (o *GetSecurityGroupNotFound) Error() string {
	return fmt.Sprintf("[GET /security-groups/{id}][%d] getSecurityGroupNotFound  %+v", 404, o.Payload)
}

func (o *GetSecurityGroupNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetSecurityGroupNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSecurityGroupInternalServerError creates a GetSecurityGroupInternalServerError with default headers values
func NewGetSecurityGroupInternalServerError() *GetSecurityGroupInternalServerError {
	return &GetSecurityGroupInternalServerError{}
}

/*
GetSecurityGroupInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetSecurityGroupInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *GetSecurityGroupInternalServerError) Error() string {
	return fmt.Sprintf("[GET /security-groups/{id}][%d] getSecurityGroupInternalServerError  %+v", 500, o.Payload)
}

func (o *GetSecurityGroupInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetSecurityGroupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
