// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"quortex.io/kubestitute/clients/ec2adapter/models"
)

// RemoveSecurityGroupReader is a Reader for the RemoveSecurityGroup structure.
type RemoveSecurityGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveSecurityGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRemoveSecurityGroupNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRemoveSecurityGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRemoveSecurityGroupForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRemoveSecurityGroupInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRemoveSecurityGroupNoContent creates a RemoveSecurityGroupNoContent with default headers values
func NewRemoveSecurityGroupNoContent() *RemoveSecurityGroupNoContent {
	return &RemoveSecurityGroupNoContent{}
}

/*RemoveSecurityGroupNoContent handles this case with default header values.

No Content
*/
type RemoveSecurityGroupNoContent struct {
	Payload string
}

func (o *RemoveSecurityGroupNoContent) Error() string {
	return fmt.Sprintf("[DELETE /security-groups/{id}/associate][%d] removeSecurityGroupNoContent  %+v", 204, o.Payload)
}

func (o *RemoveSecurityGroupNoContent) GetPayload() string {
	return o.Payload
}

func (o *RemoveSecurityGroupNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveSecurityGroupBadRequest creates a RemoveSecurityGroupBadRequest with default headers values
func NewRemoveSecurityGroupBadRequest() *RemoveSecurityGroupBadRequest {
	return &RemoveSecurityGroupBadRequest{}
}

/*RemoveSecurityGroupBadRequest handles this case with default header values.

Bad Request
*/
type RemoveSecurityGroupBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *RemoveSecurityGroupBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /security-groups/{id}/associate][%d] removeSecurityGroupBadRequest  %+v", 400, o.Payload)
}

func (o *RemoveSecurityGroupBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *RemoveSecurityGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveSecurityGroupForbidden creates a RemoveSecurityGroupForbidden with default headers values
func NewRemoveSecurityGroupForbidden() *RemoveSecurityGroupForbidden {
	return &RemoveSecurityGroupForbidden{}
}

/*RemoveSecurityGroupForbidden handles this case with default header values.

Forbidden
*/
type RemoveSecurityGroupForbidden struct {
	Payload *models.ErrorResponse
}

func (o *RemoveSecurityGroupForbidden) Error() string {
	return fmt.Sprintf("[DELETE /security-groups/{id}/associate][%d] removeSecurityGroupForbidden  %+v", 403, o.Payload)
}

func (o *RemoveSecurityGroupForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *RemoveSecurityGroupForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoveSecurityGroupInternalServerError creates a RemoveSecurityGroupInternalServerError with default headers values
func NewRemoveSecurityGroupInternalServerError() *RemoveSecurityGroupInternalServerError {
	return &RemoveSecurityGroupInternalServerError{}
}

/*RemoveSecurityGroupInternalServerError handles this case with default header values.

Internal Server Error
*/
type RemoveSecurityGroupInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *RemoveSecurityGroupInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /security-groups/{id}/associate][%d] removeSecurityGroupInternalServerError  %+v", 500, o.Payload)
}

func (o *RemoveSecurityGroupInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *RemoveSecurityGroupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
