// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"quortex.io/kubestitute/clients/ec2adapter/models"
)

// NewRevokeSecurityGroupEgressParams creates a new RevokeSecurityGroupEgressParams object
// with the default values initialized.
func NewRevokeSecurityGroupEgressParams() *RevokeSecurityGroupEgressParams {
	var ()
	return &RevokeSecurityGroupEgressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRevokeSecurityGroupEgressParamsWithTimeout creates a new RevokeSecurityGroupEgressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRevokeSecurityGroupEgressParamsWithTimeout(timeout time.Duration) *RevokeSecurityGroupEgressParams {
	var ()
	return &RevokeSecurityGroupEgressParams{

		timeout: timeout,
	}
}

// NewRevokeSecurityGroupEgressParamsWithContext creates a new RevokeSecurityGroupEgressParams object
// with the default values initialized, and the ability to set a context for a request
func NewRevokeSecurityGroupEgressParamsWithContext(ctx context.Context) *RevokeSecurityGroupEgressParams {
	var ()
	return &RevokeSecurityGroupEgressParams{

		Context: ctx,
	}
}

// NewRevokeSecurityGroupEgressParamsWithHTTPClient creates a new RevokeSecurityGroupEgressParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRevokeSecurityGroupEgressParamsWithHTTPClient(client *http.Client) *RevokeSecurityGroupEgressParams {
	var ()
	return &RevokeSecurityGroupEgressParams{
		HTTPClient: client,
	}
}

/*
RevokeSecurityGroupEgressParams contains all the parameters to send to the API endpoint
for the revoke security group egress operation typically these are written to a http.Request
*/
type RevokeSecurityGroupEgressParams struct {

	/*ID
	  The SecurityGroup ID

	*/
	ID string
	/*Request
	  The SecurityGroup Permission request

	*/
	Request *models.SecurityGroupPermissionRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the revoke security group egress params
func (o *RevokeSecurityGroupEgressParams) WithTimeout(timeout time.Duration) *RevokeSecurityGroupEgressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the revoke security group egress params
func (o *RevokeSecurityGroupEgressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the revoke security group egress params
func (o *RevokeSecurityGroupEgressParams) WithContext(ctx context.Context) *RevokeSecurityGroupEgressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the revoke security group egress params
func (o *RevokeSecurityGroupEgressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the revoke security group egress params
func (o *RevokeSecurityGroupEgressParams) WithHTTPClient(client *http.Client) *RevokeSecurityGroupEgressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the revoke security group egress params
func (o *RevokeSecurityGroupEgressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the revoke security group egress params
func (o *RevokeSecurityGroupEgressParams) WithID(id string) *RevokeSecurityGroupEgressParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the revoke security group egress params
func (o *RevokeSecurityGroupEgressParams) SetID(id string) {
	o.ID = id
}

// WithRequest adds the request to the revoke security group egress params
func (o *RevokeSecurityGroupEgressParams) WithRequest(request *models.SecurityGroupPermissionRequest) *RevokeSecurityGroupEgressParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the revoke security group egress params
func (o *RevokeSecurityGroupEgressParams) SetRequest(request *models.SecurityGroupPermissionRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *RevokeSecurityGroupEgressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
