// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"quortex.io/kubestitute/clients/ec2adapter/models"
)

// RevokeSecurityGroupIngressReader is a Reader for the RevokeSecurityGroupIngress structure.
type RevokeSecurityGroupIngressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RevokeSecurityGroupIngressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRevokeSecurityGroupIngressNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRevokeSecurityGroupIngressBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRevokeSecurityGroupIngressForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRevokeSecurityGroupIngressNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRevokeSecurityGroupIngressInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRevokeSecurityGroupIngressNoContent creates a RevokeSecurityGroupIngressNoContent with default headers values
func NewRevokeSecurityGroupIngressNoContent() *RevokeSecurityGroupIngressNoContent {
	return &RevokeSecurityGroupIngressNoContent{}
}

/*
RevokeSecurityGroupIngressNoContent handles this case with default header values.

No Content
*/
type RevokeSecurityGroupIngressNoContent struct {
	Payload string
}

func (o *RevokeSecurityGroupIngressNoContent) Error() string {
	return fmt.Sprintf("[DELETE /security-groups/{id}/ingress][%d] revokeSecurityGroupIngressNoContent  %+v", 204, o.Payload)
}

func (o *RevokeSecurityGroupIngressNoContent) GetPayload() string {
	return o.Payload
}

func (o *RevokeSecurityGroupIngressNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevokeSecurityGroupIngressBadRequest creates a RevokeSecurityGroupIngressBadRequest with default headers values
func NewRevokeSecurityGroupIngressBadRequest() *RevokeSecurityGroupIngressBadRequest {
	return &RevokeSecurityGroupIngressBadRequest{}
}

/*
RevokeSecurityGroupIngressBadRequest handles this case with default header values.

Bad Request
*/
type RevokeSecurityGroupIngressBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *RevokeSecurityGroupIngressBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /security-groups/{id}/ingress][%d] revokeSecurityGroupIngressBadRequest  %+v", 400, o.Payload)
}

func (o *RevokeSecurityGroupIngressBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *RevokeSecurityGroupIngressBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevokeSecurityGroupIngressForbidden creates a RevokeSecurityGroupIngressForbidden with default headers values
func NewRevokeSecurityGroupIngressForbidden() *RevokeSecurityGroupIngressForbidden {
	return &RevokeSecurityGroupIngressForbidden{}
}

/*
RevokeSecurityGroupIngressForbidden handles this case with default header values.

Forbidden
*/
type RevokeSecurityGroupIngressForbidden struct {
	Payload *models.ErrorResponse
}

func (o *RevokeSecurityGroupIngressForbidden) Error() string {
	return fmt.Sprintf("[DELETE /security-groups/{id}/ingress][%d] revokeSecurityGroupIngressForbidden  %+v", 403, o.Payload)
}

func (o *RevokeSecurityGroupIngressForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *RevokeSecurityGroupIngressForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevokeSecurityGroupIngressNotFound creates a RevokeSecurityGroupIngressNotFound with default headers values
func NewRevokeSecurityGroupIngressNotFound() *RevokeSecurityGroupIngressNotFound {
	return &RevokeSecurityGroupIngressNotFound{}
}

/*
RevokeSecurityGroupIngressNotFound handles this case with default header values.

Not Found
*/
type RevokeSecurityGroupIngressNotFound struct {
	Payload *models.ErrorResponse
}

func (o *RevokeSecurityGroupIngressNotFound) Error() string {
	return fmt.Sprintf("[DELETE /security-groups/{id}/ingress][%d] revokeSecurityGroupIngressNotFound  %+v", 404, o.Payload)
}

func (o *RevokeSecurityGroupIngressNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *RevokeSecurityGroupIngressNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevokeSecurityGroupIngressInternalServerError creates a RevokeSecurityGroupIngressInternalServerError with default headers values
func NewRevokeSecurityGroupIngressInternalServerError() *RevokeSecurityGroupIngressInternalServerError {
	return &RevokeSecurityGroupIngressInternalServerError{}
}

/*
RevokeSecurityGroupIngressInternalServerError handles this case with default header values.

Internal Server Error
*/
type RevokeSecurityGroupIngressInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *RevokeSecurityGroupIngressInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /security-groups/{id}/ingress][%d] revokeSecurityGroupIngressInternalServerError  %+v", 500, o.Payload)
}

func (o *RevokeSecurityGroupIngressInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *RevokeSecurityGroupIngressInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
