// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"quortex.io/kubestitute/clients/ec2adapter/models"
)

// RevokeSecurityGroupEgressReader is a Reader for the RevokeSecurityGroupEgress structure.
type RevokeSecurityGroupEgressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RevokeSecurityGroupEgressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRevokeSecurityGroupEgressNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRevokeSecurityGroupEgressBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRevokeSecurityGroupEgressForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRevokeSecurityGroupEgressNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRevokeSecurityGroupEgressInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRevokeSecurityGroupEgressNoContent creates a RevokeSecurityGroupEgressNoContent with default headers values
func NewRevokeSecurityGroupEgressNoContent() *RevokeSecurityGroupEgressNoContent {
	return &RevokeSecurityGroupEgressNoContent{}
}

/*
RevokeSecurityGroupEgressNoContent handles this case with default header values.

No Content
*/
type RevokeSecurityGroupEgressNoContent struct {
	Payload string
}

func (o *RevokeSecurityGroupEgressNoContent) Error() string {
	return fmt.Sprintf("[DELETE /security-groups/{id}/egress][%d] revokeSecurityGroupEgressNoContent  %+v", 204, o.Payload)
}

func (o *RevokeSecurityGroupEgressNoContent) GetPayload() string {
	return o.Payload
}

func (o *RevokeSecurityGroupEgressNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevokeSecurityGroupEgressBadRequest creates a RevokeSecurityGroupEgressBadRequest with default headers values
func NewRevokeSecurityGroupEgressBadRequest() *RevokeSecurityGroupEgressBadRequest {
	return &RevokeSecurityGroupEgressBadRequest{}
}

/*
RevokeSecurityGroupEgressBadRequest handles this case with default header values.

Bad Request
*/
type RevokeSecurityGroupEgressBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *RevokeSecurityGroupEgressBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /security-groups/{id}/egress][%d] revokeSecurityGroupEgressBadRequest  %+v", 400, o.Payload)
}

func (o *RevokeSecurityGroupEgressBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *RevokeSecurityGroupEgressBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevokeSecurityGroupEgressForbidden creates a RevokeSecurityGroupEgressForbidden with default headers values
func NewRevokeSecurityGroupEgressForbidden() *RevokeSecurityGroupEgressForbidden {
	return &RevokeSecurityGroupEgressForbidden{}
}

/*
RevokeSecurityGroupEgressForbidden handles this case with default header values.

Forbidden
*/
type RevokeSecurityGroupEgressForbidden struct {
	Payload *models.ErrorResponse
}

func (o *RevokeSecurityGroupEgressForbidden) Error() string {
	return fmt.Sprintf("[DELETE /security-groups/{id}/egress][%d] revokeSecurityGroupEgressForbidden  %+v", 403, o.Payload)
}

func (o *RevokeSecurityGroupEgressForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *RevokeSecurityGroupEgressForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevokeSecurityGroupEgressNotFound creates a RevokeSecurityGroupEgressNotFound with default headers values
func NewRevokeSecurityGroupEgressNotFound() *RevokeSecurityGroupEgressNotFound {
	return &RevokeSecurityGroupEgressNotFound{}
}

/*
RevokeSecurityGroupEgressNotFound handles this case with default header values.

Not Found
*/
type RevokeSecurityGroupEgressNotFound struct {
	Payload *models.ErrorResponse
}

func (o *RevokeSecurityGroupEgressNotFound) Error() string {
	return fmt.Sprintf("[DELETE /security-groups/{id}/egress][%d] revokeSecurityGroupEgressNotFound  %+v", 404, o.Payload)
}

func (o *RevokeSecurityGroupEgressNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *RevokeSecurityGroupEgressNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRevokeSecurityGroupEgressInternalServerError creates a RevokeSecurityGroupEgressInternalServerError with default headers values
func NewRevokeSecurityGroupEgressInternalServerError() *RevokeSecurityGroupEgressInternalServerError {
	return &RevokeSecurityGroupEgressInternalServerError{}
}

/*
RevokeSecurityGroupEgressInternalServerError handles this case with default header values.

Internal Server Error
*/
type RevokeSecurityGroupEgressInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *RevokeSecurityGroupEgressInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /security-groups/{id}/egress][%d] revokeSecurityGroupEgressInternalServerError  %+v", 500, o.Payload)
}

func (o *RevokeSecurityGroupEgressInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *RevokeSecurityGroupEgressInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
