// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"quortex.io/kubestitute/clients/ec2adapter/models"
)

// SetAutoscalingGroupDesiredCapacityReader is a Reader for the SetAutoscalingGroupDesiredCapacity structure.
type SetAutoscalingGroupDesiredCapacityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetAutoscalingGroupDesiredCapacityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetAutoscalingGroupDesiredCapacityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSetAutoscalingGroupDesiredCapacityBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSetAutoscalingGroupDesiredCapacityForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSetAutoscalingGroupDesiredCapacityNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSetAutoscalingGroupDesiredCapacityInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSetAutoscalingGroupDesiredCapacityOK creates a SetAutoscalingGroupDesiredCapacityOK with default headers values
func NewSetAutoscalingGroupDesiredCapacityOK() *SetAutoscalingGroupDesiredCapacityOK {
	return &SetAutoscalingGroupDesiredCapacityOK{}
}

/*SetAutoscalingGroupDesiredCapacityOK handles this case with default header values.

OK
*/
type SetAutoscalingGroupDesiredCapacityOK struct {
	Payload *models.SecurityGroup
}

func (o *SetAutoscalingGroupDesiredCapacityOK) Error() string {
	return fmt.Sprintf("[PUT /autoscaling-groups/{name}/desired-capacity][%d] setAutoscalingGroupDesiredCapacityOK  %+v", 200, o.Payload)
}

func (o *SetAutoscalingGroupDesiredCapacityOK) GetPayload() *models.SecurityGroup {
	return o.Payload
}

func (o *SetAutoscalingGroupDesiredCapacityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SecurityGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetAutoscalingGroupDesiredCapacityBadRequest creates a SetAutoscalingGroupDesiredCapacityBadRequest with default headers values
func NewSetAutoscalingGroupDesiredCapacityBadRequest() *SetAutoscalingGroupDesiredCapacityBadRequest {
	return &SetAutoscalingGroupDesiredCapacityBadRequest{}
}

/*SetAutoscalingGroupDesiredCapacityBadRequest handles this case with default header values.

Bad Request
*/
type SetAutoscalingGroupDesiredCapacityBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *SetAutoscalingGroupDesiredCapacityBadRequest) Error() string {
	return fmt.Sprintf("[PUT /autoscaling-groups/{name}/desired-capacity][%d] setAutoscalingGroupDesiredCapacityBadRequest  %+v", 400, o.Payload)
}

func (o *SetAutoscalingGroupDesiredCapacityBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *SetAutoscalingGroupDesiredCapacityBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetAutoscalingGroupDesiredCapacityForbidden creates a SetAutoscalingGroupDesiredCapacityForbidden with default headers values
func NewSetAutoscalingGroupDesiredCapacityForbidden() *SetAutoscalingGroupDesiredCapacityForbidden {
	return &SetAutoscalingGroupDesiredCapacityForbidden{}
}

/*SetAutoscalingGroupDesiredCapacityForbidden handles this case with default header values.

Forbidden
*/
type SetAutoscalingGroupDesiredCapacityForbidden struct {
	Payload *models.ErrorResponse
}

func (o *SetAutoscalingGroupDesiredCapacityForbidden) Error() string {
	return fmt.Sprintf("[PUT /autoscaling-groups/{name}/desired-capacity][%d] setAutoscalingGroupDesiredCapacityForbidden  %+v", 403, o.Payload)
}

func (o *SetAutoscalingGroupDesiredCapacityForbidden) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *SetAutoscalingGroupDesiredCapacityForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetAutoscalingGroupDesiredCapacityNotFound creates a SetAutoscalingGroupDesiredCapacityNotFound with default headers values
func NewSetAutoscalingGroupDesiredCapacityNotFound() *SetAutoscalingGroupDesiredCapacityNotFound {
	return &SetAutoscalingGroupDesiredCapacityNotFound{}
}

/*SetAutoscalingGroupDesiredCapacityNotFound handles this case with default header values.

Not Found
*/
type SetAutoscalingGroupDesiredCapacityNotFound struct {
	Payload *models.ErrorResponse
}

func (o *SetAutoscalingGroupDesiredCapacityNotFound) Error() string {
	return fmt.Sprintf("[PUT /autoscaling-groups/{name}/desired-capacity][%d] setAutoscalingGroupDesiredCapacityNotFound  %+v", 404, o.Payload)
}

func (o *SetAutoscalingGroupDesiredCapacityNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *SetAutoscalingGroupDesiredCapacityNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetAutoscalingGroupDesiredCapacityInternalServerError creates a SetAutoscalingGroupDesiredCapacityInternalServerError with default headers values
func NewSetAutoscalingGroupDesiredCapacityInternalServerError() *SetAutoscalingGroupDesiredCapacityInternalServerError {
	return &SetAutoscalingGroupDesiredCapacityInternalServerError{}
}

/*SetAutoscalingGroupDesiredCapacityInternalServerError handles this case with default header values.

Internal Server Error
*/
type SetAutoscalingGroupDesiredCapacityInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *SetAutoscalingGroupDesiredCapacityInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /autoscaling-groups/{name}/desired-capacity][%d] setAutoscalingGroupDesiredCapacityInternalServerError  %+v", 500, o.Payload)
}

func (o *SetAutoscalingGroupDesiredCapacityInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *SetAutoscalingGroupDesiredCapacityInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
