// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"quortex.io/kubestitute/clients/ec2adapter/models"
)

// NewSetAutoscalingGroupDesiredCapacityParams creates a new SetAutoscalingGroupDesiredCapacityParams object
// with the default values initialized.
func NewSetAutoscalingGroupDesiredCapacityParams() *SetAutoscalingGroupDesiredCapacityParams {
	var ()
	return &SetAutoscalingGroupDesiredCapacityParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetAutoscalingGroupDesiredCapacityParamsWithTimeout creates a new SetAutoscalingGroupDesiredCapacityParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetAutoscalingGroupDesiredCapacityParamsWithTimeout(timeout time.Duration) *SetAutoscalingGroupDesiredCapacityParams {
	var ()
	return &SetAutoscalingGroupDesiredCapacityParams{

		timeout: timeout,
	}
}

// NewSetAutoscalingGroupDesiredCapacityParamsWithContext creates a new SetAutoscalingGroupDesiredCapacityParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetAutoscalingGroupDesiredCapacityParamsWithContext(ctx context.Context) *SetAutoscalingGroupDesiredCapacityParams {
	var ()
	return &SetAutoscalingGroupDesiredCapacityParams{

		Context: ctx,
	}
}

// NewSetAutoscalingGroupDesiredCapacityParamsWithHTTPClient creates a new SetAutoscalingGroupDesiredCapacityParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetAutoscalingGroupDesiredCapacityParamsWithHTTPClient(client *http.Client) *SetAutoscalingGroupDesiredCapacityParams {
	var ()
	return &SetAutoscalingGroupDesiredCapacityParams{
		HTTPClient: client,
	}
}

/*
SetAutoscalingGroupDesiredCapacityParams contains all the parameters to send to the API endpoint
for the set autoscaling group desired capacity operation typically these are written to a http.Request
*/
type SetAutoscalingGroupDesiredCapacityParams struct {

	/*Name
	  The AutoscalingGroup name

	*/
	Name string
	/*Request
	  The AutoscalingGroup SetDesiredCapacity request

	*/
	Request *models.SetDesiredCapacityRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set autoscaling group desired capacity params
func (o *SetAutoscalingGroupDesiredCapacityParams) WithTimeout(timeout time.Duration) *SetAutoscalingGroupDesiredCapacityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set autoscaling group desired capacity params
func (o *SetAutoscalingGroupDesiredCapacityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set autoscaling group desired capacity params
func (o *SetAutoscalingGroupDesiredCapacityParams) WithContext(ctx context.Context) *SetAutoscalingGroupDesiredCapacityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set autoscaling group desired capacity params
func (o *SetAutoscalingGroupDesiredCapacityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set autoscaling group desired capacity params
func (o *SetAutoscalingGroupDesiredCapacityParams) WithHTTPClient(client *http.Client) *SetAutoscalingGroupDesiredCapacityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set autoscaling group desired capacity params
func (o *SetAutoscalingGroupDesiredCapacityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the set autoscaling group desired capacity params
func (o *SetAutoscalingGroupDesiredCapacityParams) WithName(name string) *SetAutoscalingGroupDesiredCapacityParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the set autoscaling group desired capacity params
func (o *SetAutoscalingGroupDesiredCapacityParams) SetName(name string) {
	o.Name = name
}

// WithRequest adds the request to the set autoscaling group desired capacity params
func (o *SetAutoscalingGroupDesiredCapacityParams) WithRequest(request *models.SetDesiredCapacityRequest) *SetAutoscalingGroupDesiredCapacityParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the set autoscaling group desired capacity params
func (o *SetAutoscalingGroupDesiredCapacityParams) SetRequest(request *models.SetDesiredCapacityRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *SetAutoscalingGroupDesiredCapacityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
