# Build and push Docker image to docker hub

name: Build

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - develop
      - master
    tags:
      - "*"

jobs:
  build-and-push:
    name: BuildAndPush
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      # This step uses action-hub docker action: https://github.com/actions-hub/docker
      - name: Login to docker hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build docker image
      - name: Build docker image
        if: success()
        shell: bash
        env:
          IMG: quortexio/kubestitute:${IMAGE_TAG}
        run: |
          make docker-build docker-push
